name: Botagaue Actions
on: workflow_dispatch
jobs:
 BUILD_AND_PUBLISH:
  runs-on: ubuntu-latest
  steps:
   - name: code checkout
     uses: actions/checkout@v4
   
   - name: Install kubectl
     uses: azure/setup-kubectl@v2.0
     with:
       version: 'v1.27.0' 
     id: install
   - name: Configure AWS Credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: ap-south-1  
   - name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
   
   - name: Build and push
     uses: docker/build-push-action@v4
     with:
       context: .
       push: true
       tags: ${{ secrets.DOCKERHUB_USERNAME }}/goimages:latest   
   - name: Update kube config
     run: aws eks update-kubeconfig --name ToDo-App
      
   
   - name: Deploy go helm chart to EKS
     run: |
      helm install nodeapp ./node-app-chart
